# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
aws_region = "us-east-1"
ddb_path   = "../ddb"
iam_path   = "../iam"
name       = "best-cat-2025-09-24-2359"
s3_path    = "../s3"
