# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "terragrunt-to-terralith-tfstate-2025-11-17-0038"
    encrypt      = true
    key          = "prod/.terragrunt-stack/iam/tofu.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
